### ISSUE TITLE
Evaluation Error: Missing title at index 0. The title expression resulted in an undef title 

### ISSUE THREAD

**Issue by zdtsw** [cristifalcas/puppet-flannel#5]
by just calling "include flannel::install", I got an error as subject.
checking install.pp:
 package { [$flannel::package_name]: ensure => $flannel::ensure, }

How  this works?
should it not be something like below: (esp. the params part)
 package { $flannel::params::package_name:
           ensure => $flannel::params::ensure, 
 }

**Comment by cristifalcas** [comment]
You should not call flannel::install directly. It needs parameters from the main flannel class, which has defaults in flannel::params.

**Comment by zdtsw** [comment]
ok, I see.
